### PR TITLE
Made necessary changes with appstream metadata and removed some `build-packages`

### PR DESCRIPTION
**Pull request by soumyaDghosh**

### CODE REVIEW

**Review by alexmurray — DISMISSED** [review]
Thanks for this - particularly the appstream metadata fix.

**Comment by alexmurray** [comment]
Hmm have you actually tested this - when I built the snap locally and ran it it failed to launch and I see the following output:

```
± amberol 
Warning: Schema “org.gnome.system.locale” has path “/system/locale/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy” has path “/system/proxy/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy.http” has path “/system/proxy/http/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy.https” has path “/system/proxy/https/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy.ftp” has path “/system/proxy/ftp/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy.socks” has path “/system/proxy/socks/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
/snap/amberol/x1/usr/bin/amberol: symbol lookup error: /snap/amberol/x1/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-4.so.1: undefined symbol: hb_font_get_var_coords_design
```

I appreciate you trying to help but please it is taking a lot of my time to just double check your work and finding all these issues - please appropriately test any further changes. This clearly needs fixing.

**Comment by alexmurray** [comment]
> Hmm have you actually tested this - when I built the snap locally and ran it it failed to launch and I see the following output:
> 
> ```
> ± amberol 
> Warning: Schema “org.gnome.system.locale” has path “/system/locale/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
> Warning: Schema “org.gnome.system.proxy” has path “/system/proxy/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
> Warning: Schema “org.gnome.system.proxy.http” has path “/system/proxy/http/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
> Warning: Schema “org.gnome.system.proxy.https” has path “/system/proxy/https/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
> Warning: Schema “org.gnome.system.proxy.ftp” has path “/system/proxy/ftp/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
> Warning: Schema “org.gnome.system.proxy.socks” has path “/system/proxy/socks/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
> /snap/amberol/x1/usr/bin/amberol: symbol lookup error: /snap/amberol/x1/gnome-platform/usr/lib/x86_64-linux-gnu/libgtk-4.so.1: undefined symbol: hb_font_get_var_coords_design
> ```
> 
> I appreciate you trying to help but please it is taking a lot of my time to just double check your work and finding all these issues - please appropriately test any further changes. This clearly needs fixing.

**Review by alexmurray — CHANGES_REQUESTED** [review]
This needs changing as currently the snap fails to launch at runtime for me when built locally from this PR.

**Comment by soumyaDghosh** [comment]
Okay, firstly I am extremely sorry, because I thought that I'm removing only those files, which are already in `gnome-sdk`, but seems like amberol `0.9.1` needs libadwaita-1-0 staged as a package. Now, I staged that package and updated amberol to latest upstream, `0.10.2` and now I'm getting new errors,

```
 soumyaxubuntu  soumyas-gf63-thin-11uc  ../amberol-snap  main ◔  amberol
Warning: Schema “org.gnome.system.locale” has path “/system/locale/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy” has path “/system/proxy/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy.http” has path “/system/proxy/http/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy.https” has path “/system/proxy/https/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy.ftp” has path “/system/proxy/ftp/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
Warning: Schema “org.gnome.system.proxy.socks” has path “/system/proxy/socks/”.  Paths starting with “/apps/”, “/desktop/” or “/system/” are deprecated.
/snap/amberol/x2/usr/bin/amberol: symbol lookup error: /snap/amberol/x2/usr/bin/amberol: undefined symbol: gtk_inscription_get_text
```
Seems like, some kind of version mismanagement with either gtk4 or harfbuzz files, I also tried some tricks to decrease the file size, a little, but not a significant help.

**Comment by soumyaDghosh** [comment]
```
name: amberol
version: 0.10.2
adopt-info: amberol
base: core22
grade: stable
confinement: strict
license: GPL-3.0+
compression: lzo

slots:
  # for GtkApplication registration
  amberol:
    interface: dbus
    bus: session
    name: io.bassi.Amberol
  mpris:
    name: Amberol

apps:
  amberol:
    environment:
      XDG_DATA_DIRS: $SNAP/share:$XDG_DATA_DIRS
    command: usr/bin/amberol
    extensions: [gnome]
    desktop: usr/share/applications/io.bassi.Amberol.desktop
    common-id: io.bassi.Amberol
    plugs:
      - home
      - audio-playback
      - removable-media
      - mount-observe
      - hostname-control
    slots:
      - mpris

parts:
  amberol:
    source: https://gitlab.gnome.org/World/amberol.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    plugin: meson
    meson-parameters:
      - --prefix=/snap/amberol/current/usr
      - -Dbuildtype=release
      - -Doptimization=2
    parse-info: [usr/share/appdata/io.bassi.Amberol.appdata.xml]
    organize:
      snap/amberol/current: .
    build-packages:
      - intltool
      - gnome-common
      - rustc
      - cargo
      - libappstream-glib-dev
      - libappstream-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - execstack
    stage-packages:
      - libgstreamer-plugins-base1.0-0
      - libgstreamer1.0-0
      - gstreamer1.0-plugins-base
      - gstreamer1.0-plugins-good
      - gstreamer1.0-plugins-bad
      - gstreamer1.0-plugins-ugly
      - libadwaita-1-0
      - libdbus-1-3
    override-pull: |
      craftctl default
      # snapd can't use a name like io.bassi.Amberol for mpris
      # (since it contains periods) so instead make this just Amberol
      sed -i '0,/APPLICATION_ID.to_string()/{s/APPLICATION_ID.to_string()/"Amberol".to_string()/}' src/audio/mpris_controller.rs
      sed -i '/^\[profile\.release\]$/a lto = true\ncodegen-units = 1\nopt-level = "s"' Cargo.toml
    override-prime: |
      set -eu
      craftctl default
      # try remove execstack on armhf
      for f in usr/lib/arm-linux-gnueabihf/libde265.so.0.1.1 usr/lib/arm-linux-gnueabihf/libmpeg2.so.0.1.0; do
        if [ -f $f ]; then
          execstack -c $f
        fi
      done
```

Latest snapcraft.yaml

**Pull request closed without merging**
